export const keys = {
  GET_TOP_MOVIES: "GET_TOP_MOVIES",
  SEARCH_MOVIES: "SEARCH_MOVIES",
  GET_MOVIE_DETAILS: "GET_MOVIE_DETAILS",
  SHOW_MOVIE_DETAILS: "SHOW_MOVIE_DETAILS",
  HIDE_MOVIE_DETAILS: "HIDE_MOVIE_DETAILS",
  LOGIN_USER: "LOGIN_USER",
};
